### ISSUE TITLE
upgrade checkout form not working

### ISSUE THREAD

**Issue by SamHz** [magepal/magento2-customshippingrate#1]
could you get me some help? use your module checkout form not working,it's about rules.js error,i can't  repair it,checkout window is not loading.please fix this problem

**Comment by srenon** [comment]
What version of magento 2.x are you using?

**Comment by SamHz** [comment]
@srenon magento version 2.1.2,now i remove your module,it's working.but, i want to use your code  and learn how to rewrite my shipping method.please tell me.do you have any good ideas?thanks a lot.

**Comment by srenon** [comment]
Are you getting this error in the Admin or Frontend?

Are you run any other custom module that customizes checkout?

Can you disable any other custom module (if any) and let me know if you are still getting this error

I just test on M2.1.3 CE

![image](https://cloud.githubusercontent.com/assets/1415141/24250194/65de6e3a-0fac-11e7-8161-0fcd2299e2ac.png)

Can you provide some screenshots and exact error msg, I originally tested on 2.1.2 CE
