### ISSUE TITLE
Error During Compilation

### ISSUE THREAD

**Issue by iamkerly** [magepal/magento2-customshippingrate#2]
MagePal\CustomShippingRate\Helper\Data
Incorrect dependency in class MagePal\CustomShippingRate\Helper\Data in /home/xxx/public_html/mage214/vendor/magepal/magento2-customshippingrate/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object

How can I fix this?

**Comment by srenon** [comment]
@simadmin ... please download the latest version and let me know if you still having issue
